[solana-core]
CRDS_GOSSIP_NUM_ACTIVE = 29
CRDS_GOSSIP_PUSH_FANOUT = 6
CRDS_GOSSIP_PUSH_MSG_TIMEOUT_MS = 30000
CRDS_GOSSIP_PRUNE_MSG_TIMEOUT_MS = 450
CRDS_GOSSIP_PRUNE_STAKE_THRESHOLD_PCT = 0.15
CRDS_GOSSIP_PRUNE_MIN_INGRESS_NODES = 3
PUSH_ACTIVE_TIMEOUT_MS = 60000
MAX_PUSHED_TO_TIMEOUT_MS = 50000
RECV_BATCH_MAX_CPU = 1000
RECV_BATCH_MAX_GPU = 5000
FORWARD_TRANSACTIONS_TO_LEADER_AT_SLOT_OFFSET = 1
NUM_THREADS = 4
TOTAL_BUFFERED_PACKETS = 500000
MAX_NUM_TRANSACTIONS_PER_BATCH = 110
LARGEST_CONFIRMED_ROOT_UPLOAD_DELAY = 90
NUM_INSERT_THREADS = 2
RECEIVE_ENTRY_COUNT_THRESHOLD = 9
NUM_BAD_SLOTS = 9
SLOT_TO_RESOLVE = 30
BROADCAST_PEER_UPDATE_INTERVAL_MS = 800
DATA_PLANE_FANOUT = 200
GOSSIP_SLEEP_MILLIS = 102
MAX_CRDS_OBJECT_SIZE = 928
MAX_PROTOCOL_HEADER_SIZE = 214
MAX_SNAPSHOT_HASHES = 14
GOSSIP_PING_CACHE_CAPACITY = 16384
GOSSIP_PING_CACHE_TTL = 600
VOTE_THRESHOLD_DEPTH = 8
SWITCH_FORK_THRESHOLD = 0.4
CRDS_GOSSIP_DEFAULT_BLOOM_ITEMS = 500
CRDS_GOSSIP_PULL_CRDS_TIMEOUT_MS = 15000
CRDS_GOSSIP_PULL_MSG_TIMEOUT_MS = 60000
FAILED_INSERTS_RETENTION_MS = 20000
DEFAULT_MAX_LEDGER_SHREDS = 200000000
DEFAULT_MIN_MAX_LEDGER_SHREDS = 50000000
DEFAULT_PURGE_SLOT_INTERVAL = 512
GRACE_TICKS_FACTOR = 2
MAX_GRACE_SLOTS = 2
MAX_ENTRY_RECV_PER_ITER = 510
SUPERMINORITY_THRESHOLD = 0.3333333
MAX_UNCONFIRMED_SLOTS = 5
[solana-perf]
NUM_PACKETS = 8192
PACKETS_PER_BATCH = 256
[solana-runtime]
INTERVAL_MS = 100
SHRUNKEN_ACCOUNT_PER_SEC = 250
CLEAN_INTERVAL_BLOCKS = 100
PAGE_SIZE = 4096
DEFAULT_NUM_THREADS = 8
DEFAULT_NUM_DIRS = 4
ITER_BATCH_SIZE = 1000
MAX_LEADER_SCHEDULE_STAKES = 5
VOTE_THRESHOLD_SIZE = 0.6666667
BOOTSTRAP_VALIDATOR_LAMPORTS = 42
MAX_STREAM_SIZE = 3422552064
NUM_BLOCKHASH_CONFIRMATIONS = 3
[solana-ramp-tps]
MIN_LEADER_SLOT_PCT = 80.0
[solana-ledger]
NUM_BLOCKS_TO_UPLOAD_IN_PARALLEL = 32
MAX_COMPLETED_SLOTS_IN_CHANNEL = 100000
MAX_TURBINE_PROPAGATION_IN_MS = 100
MAX_DATA_SHREDS_PER_SLOT = 32768
SIGN_SHRED_GPU_MIN = 256
MAX_SCHEDULES = 10
[solana-bpf-loader-program]
DEFAULT_HEAP_SIZE = 32768
[solana-program]
DEFAULT_TICKS_PER_SECOND = 160
DEFAULT_TICKS_PER_SLOT = 63
DEFAULT_HASHES_PER_SECOND = 2000000
DEFAULT_DEV_SLOTS_PER_EPOCH = 256
DEFAULT_TARGET_LAMPORTS_PER_SIGNATURE = 10000
NUM_CONSECUTIVE_LEADER_SLOTS = 4
MAX_HASH_AGE_IN_SECONDS = 120
MAX_TRANSACTION_FORWARDING_DELAY_GPU = 2
MAX_TRANSACTION_FORWARDING_DELAY = 6
MAX_LEADER_SCHEDULE_EPOCH_OFFSET = 3
MINIMUM_SLOTS_PER_EPOCH = 32
DEFAULT_LAMPORTS_PER_BYTE_YEAR = 3480
DEFAULT_EXEMPTION_THRESHOLD = 2.0
DEFAULT_BURN_PERCENT = 50
ACCOUNT_STORAGE_OVERHEAD = 128
SLOT_MAX_ENTRIES = 512
STAKE_HISTORY_MAX_ENTRIES = 512
SLOT_HISTORY_MAX_ENTRIES = 1048576
RECENT_BLOCKHASHES_MAX_ENTRIES = 150
[solana-sdk]
DEFAULT_INITIAL = 0.08
DEFAULT_TERMINAL = 0.015
DEFAULT_TAPER = 0.15
DEFAULT_FOUNDATION = 0.05
DEFAULT_FOUNDATION_TERM = 7.0
PBKDF2_ROUNDS = 2048
PBKDF2_BYTES = 64
