[solana-core]
CRDS_GOSSIP_NUM_ACTIVE = 29
CRDS_GOSSIP_PUSH_FANOUT = 6
CRDS_GOSSIP_PUSH_MSG_TIMEOUT_MS = 27000
CRDS_GOSSIP_PRUNE_MSG_TIMEOUT_MS = 450
CRDS_GOSSIP_PRUNE_STAKE_THRESHOLD_PCT = 0.135
CRDS_GOSSIP_PRUNE_MIN_INGRESS_NODES = 3
PUSH_ACTIVE_TIMEOUT_MS = 60000
MAX_PUSHED_TO_TIMEOUT_MS = 45000
RECV_BATCH_MAX_CPU = 1100
RECV_BATCH_MAX_GPU = 5000
FORWARD_TRANSACTIONS_TO_LEADER_AT_SLOT_OFFSET = 1
NUM_THREADS = 4
TOTAL_BUFFERED_PACKETS = 550000
MAX_NUM_TRANSACTIONS_PER_BATCH = 99
LARGEST_CONFIRMED_ROOT_UPLOAD_DELAY = 81
NUM_INSERT_THREADS = 2
RECEIVE_ENTRY_COUNT_THRESHOLD = 9
NUM_BAD_SLOTS = 9
SLOT_TO_RESOLVE = 30
BROADCAST_PEER_UPDATE_INTERVAL_MS = 880
DATA_PLANE_FANOUT = 200
GOSSIP_SLEEP_MILLIS = 112
MAX_CRDS_OBJECT_SIZE = 928
MAX_PROTOCOL_HEADER_SIZE = 235
MAX_SNAPSHOT_HASHES = 14
GOSSIP_PING_CACHE_CAPACITY = 14745
GOSSIP_PING_CACHE_TTL = 660
VOTE_THRESHOLD_DEPTH = 7
SWITCH_FORK_THRESHOLD = 0.44000000000000006
CRDS_GOSSIP_DEFAULT_BLOOM_ITEMS = 500
CRDS_GOSSIP_PULL_CRDS_TIMEOUT_MS = 13500
CRDS_GOSSIP_PULL_MSG_TIMEOUT_MS = 66000
FAILED_INSERTS_RETENTION_MS = 18000
DEFAULT_MAX_LEDGER_SHREDS = 200000000
DEFAULT_MIN_MAX_LEDGER_SHREDS = 55000000
DEFAULT_PURGE_SLOT_INTERVAL = 563
GRACE_TICKS_FACTOR = 2
MAX_GRACE_SLOTS = 2
MAX_ENTRY_RECV_PER_ITER = 561
SUPERMINORITY_THRESHOLD = 0.36666663000000005
MAX_UNCONFIRMED_SLOTS = 5
[solana-perf]
NUM_PACKETS = 8192
PACKETS_PER_BATCH = 281
[solana-runtime]
INTERVAL_MS = 110
SHRUNKEN_ACCOUNT_PER_SEC = 225
CLEAN_INTERVAL_BLOCKS = 110
PAGE_SIZE = 4505
DEFAULT_NUM_THREADS = 8
DEFAULT_NUM_DIRS = 3
ITER_BATCH_SIZE = 1000
MAX_LEADER_SCHEDULE_STAKES = 5
VOTE_THRESHOLD_SIZE = 0.6666667
BOOTSTRAP_VALIDATOR_LAMPORTS = 46
MAX_STREAM_SIZE = 3080296857
NUM_BLOCKHASH_CONFIRMATIONS = 3
[solana-ramp-tps]
MIN_LEADER_SLOT_PCT = 80.0
[solana-ledger]
NUM_BLOCKS_TO_UPLOAD_IN_PARALLEL = 32
MAX_COMPLETED_SLOTS_IN_CHANNEL = 100000
MAX_TURBINE_PROPAGATION_IN_MS = 110
MAX_DATA_SHREDS_PER_SLOT = 29491
SIGN_SHRED_GPU_MIN = 256
MAX_SCHEDULES = 10
[solana-bpf-loader-program]
DEFAULT_HEAP_SIZE = 29491
[solana-program]
DEFAULT_TICKS_PER_SECOND = 176
DEFAULT_TICKS_PER_SLOT = 63
DEFAULT_HASHES_PER_SECOND = 1800000
DEFAULT_DEV_SLOTS_PER_EPOCH = 9011
DEFAULT_TARGET_LAMPORTS_PER_SIGNATURE = 9000
NUM_CONSECUTIVE_LEADER_SLOTS = 4
MAX_HASH_AGE_IN_SECONDS = 132
MAX_TRANSACTION_FORWARDING_DELAY_GPU = 2
MAX_TRANSACTION_FORWARDING_DELAY = 6
MAX_LEADER_SCHEDULE_EPOCH_OFFSET = 3
MINIMUM_SLOTS_PER_EPOCH = 35
DEFAULT_LAMPORTS_PER_BYTE_YEAR = 3828
DEFAULT_EXEMPTION_THRESHOLD = 2.0
DEFAULT_BURN_PERCENT = 55
ACCOUNT_STORAGE_OVERHEAD = 115
SLOT_MAX_ENTRIES = 460
STAKE_HISTORY_MAX_ENTRIES = 563
SLOT_HISTORY_MAX_ENTRIES = 1153433
RECENT_BLOCKHASHES_MAX_ENTRIES = 135
[solana-sdk]
DEFAULT_INITIAL = 0.08800000000000001
DEFAULT_TERMINAL = 0.015
DEFAULT_TAPER = 0.165
DEFAULT_FOUNDATION = 0.05
DEFAULT_FOUNDATION_TERM = 7.700000000000001
PBKDF2_ROUNDS = 2048
PBKDF2_BYTES = 57
