version: "3"
services:
  genesis_node:
    image: solana142
    volumes:
      - /Users/korg/PycharmProjects/velas-ss/my_volume:/my_vol
    tty: true

    command: sh -c "scp ./config/bootstrap-validator/genesis.bin /my_vol/ &&
              /bin/bash "
        # RUST_LOG='trace' USE_INSTALL=1 ./multinode-demo/bootstrap-validator.sh --gossip-host 192.168.16.2 --log /my_vol/logs_genesis4"
        # hostname -I | awk '{print $1}'
  validator:
    image: solana142
    depends_on:
      - genesis_node
    volumes:
      - /Users/korg/PycharmProjects/velas-ss/my_volume:/my_vol
    tty: true
    command: sh -c "scp /my_vol/genesis.bin ./config/bootstrap-validator/ &&
                    ls ../my_vol &&
                    /bin/bash  "
                   # USE_INSTALL=1 ./multinode-demo/validator.sh --entrypoint 192.168.16.2:8001"