version: "3"
services:
  genesis_node:
    image: solana142
    volumes:
      - /Users/korg/PycharmProjects/velas-ss/my_volume:/my_vol
    tty: true
    command: sh -c "scp ./config/bootstrap-validator/genesis.bin /my_vol/ &&
        USE_INSTALL=1 ./multinode-demo/bootstrap-validator.sh --gossip-host genesis_node --log /my_vol/logs_genesis2
        & USE_INSTALL=1 ./multinode-demo/faucet.sh"
        # RUST_LOG='trace'
  validator:
    image: solana142
    depends_on:
      - genesis_node
    volumes:
      - /Users/korg/PycharmProjects/velas-ss/my_volume:/my_vol
    tty: true
    command: sh -c "scp /my_vol/genesis.bin ./config/bootstrap-validator/ &&
             USE_INSTALL=1 ./multinode-demo/validator.sh --entrypoint genesis_node:8001 --log /my_vol/logs_valid2"
  cli:
    image: solana142
    depends_on:
      - validator
    tty: true
    command:
      sh -c "solana config set --url http://genesis_node:8899 &&
      solana validators &&
      /bin/bash "