version: "3.8"

services:
  transaction:
    image: python_trans_conf:2
    command: /bin/bash -c "cd velas-ss && python config_generator.py && cd .. &&  cp "./velas-ss/generated/config.toml" /mnt/logs && sleep 25 && python velas-ss/transaction_sender.py --tps 100 --s 5 && cp "transaction_logger.txt" /mnt/logs"
    volumes:
      - /mnt/nfs_share/solana/exp1:/mnt/logs
    networks:
      - solana_net
  genesis_node:
    image: nikromanov/solana-velas:1.5.0
    command:
      /bin/bash -c "sleep 5 && cp "/mnt/logs/config.toml" ./ && USE_INSTALL=1 ./multinode-demo/setup.sh && cp ./config/bootstrap-validator/genesis.bin /mnt/logs/ &&
                    ./multinode-demo/bootstrap-validator.sh --gossip-host genesis_node --log /mnt/logs/solana_genesis_node.txt &
                    sleep 15 && ./multinode-demo/faucet.sh"
    volumes:
      - /mnt/nfs_share/solana/exp1:/mnt/logs
    networks:
      - solana_net

  validator:
    image: nikromanov/solana-velas:1.5.0
    depends_on:
      - genesis_node
    command: /bin/bash -c "sleep 15 && cp /mnt/logs/genesis.bin ./config/bootstrap-validator/ && cp "/mnt/logs/config.toml" .
                           && ./multinode-demo/validator.sh --entrypoint genesis_node:8001 --log /mnt/logs/solana_validator_`hostname`.txt"
    volumes:
      - /mnt/nfs_share/solana/exp1:/mnt/logs
    networks:
      - solana_net
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 10
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 50M

networks:
  solana_net:
    driver: overlay
    attachable: true