version: "3.8"

services:
  genesis_node:
    image: nikromanov/solana-velas:1.5.0
    command:
      /bin/bash -c "RUST_LOG='trace' ./multinode-demo/bootstrap-validator.sh --gossip-host genesis_node --log /mnt/logs/solana_genesis_node &
                    ./multinode-demo/faucet.sh"
    volumes:
      - /mnt/nfs_share/solana/ad106_logs:/mnt/logs

  validator:
    image: nikromanov/solana-velas:1.5.0
    depends_on:
      - genesis_node
    command: /bin/bash -c "sleep 2 && ./multinode-demo/validator.sh --entrypoint genesis_node:8001 --log /mnt/logs/solana_valid10"
    volumes:
      - /mnt/nfs_share/solana/ad106_logs:/mnt/logs
  transaction:
    image: trans_sender:0.6
    depends_on:
      - genesis_node
    command: /bin/bash -c "sleep 10 && python transaction_sender.py --tps 100 --host http://genesis_node"

# python transaction_sender.py --tps 15 --host_air "http://devnet.solana.com:80"